language: node_js
node_js:
- '6.10'
script: mocha-webpack --webpack-config webpack.server-test.babel.js server/tests/*-test.js && node_modules/karma/bin/karma start karma.conf.js --single-run
addons:
  firefox: latest
services:
- mongodb
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install
deploy:
  provider: heroku
  app: staging-shiny-volunteer
  api_key:
    secure: JWY5hV7j8vNyeg1MlluAzIcWvuv+ap1pzMKCFT73UbJvo3W9/kxlTHBMljf8i3fFlShjLAwZyWADLj10eri+3aBguZLxADG5yq6YymIQvnsQydA4LTTTb/fUS16Fm2Gsyq7xY4V8TnUaShILDhPVGdxHK5ET/MJeWgffYybdi04u3XuE/3TFHD5N/tPUuqkWLaWrTAeXaq6ph7pe/sbgx0FE7vp/V8ysO6lJqSvocbp3bDTyJZgsXh1wQm5yj1ChaCEEOy87rWHIZEsHfMDULGd10tvIeP9I52ZnDmcT3XOZtNlHO1Aj35usfLHYJzukARJDeGU1/m1evscdQXQ1Enwwl5HMBcrlKLV9sAM3OafnZqyZWxMqXR7DbQ92vAvCEB88ubjx8ZwT7xEFIzUO7MKcbm9R3StMWIzVsznuU1VuuJ5Krx7gQM3ynn0AEDpgw7glBMpgceQVoPJA5v9EzPx5hUlXBe/xJ53uBH6+c6sjgwEBkaKsTv27jqnEfL9bIzwujxMDx4PNt/mTgY5yLBZ13O2Hp8I/pk6O+GxLZBWDkR3ok5nHtXcYHjBjbkETxH5nhCjTLxwxTKZkAIO3HtpPypn/yaKYwt3LCZAqX5WvtnSp3lIUHgeoes+Cmp6/DzjTCkRnMTziAylB0pY5PurPYzLwp3+Yf6NeLDmL23A=
